SET SQL_SAFE_UPDATES = 0;

DELETE FROM playerPerformance;
ALTER TABLE playerPerformance AUTO_INCREMENT = 1;

DELETE FROM coachPerformance;
ALTER TABLE coachPerformance AUTO_INCREMENT = 1;

DELETE FROM player;
ALTER TABLE player AUTO_INCREMENT = 1;

DELETE FROM coach;
ALTER TABLE coach AUTO_INCREMENT = 1;

DELETE FROM event;
ALTER TABLE event AUTO_INCREMENT = 1;

DELETE FROM game;
ALTER TABLE game AUTO_INCREMENT = 1;

DELETE FROM teamName;
ALTER TABLE teamName AUTO_INCREMENT = 1;

DELETE FROM team;
ALTER TABLE team AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 1;