USE acb;

-- Table with all the teams uniquely identified
CREATE TABLE team (
    id INTEGER PRIMARY KEY,  -- Team acb id
    founded_year INTEGER DEFAULT null
);
INSERT INTO team VALUES (0, null); -- for referees

-- Table with the teams and associated names for each season
CREATE TABLE teamname (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    team_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,  -- Name taken for a single season (depends on the sponsors)
    season INTEGER NOT NULL,  -- Season year
    FOREIGN KEY (team_id) REFERENCES team(id)
);
CREATE INDEX teamName_team_id_idx ON teamname(id);

-- Table with all the games
CREATE TABLE game (
    id INTEGER PRIMARY KEY,
    team_home_id INTEGER NOT NULL,  -- Reference to the home team id
    team_away_id INTEGER NOT NULL,  -- Reference to the away team id

    season INTEGER NOT NULL,  -- Season year
    journey INTEGER NOT NULL,  -- Number of the journey. In regular season it is generally one journey per week. In playoff it is one journey per round match.
    -- TODO: competition VARCHAR(255) NOT NULL, (ACB, Copa, SuperCopa)
    competition_phase VARCHAR(255) DEFAULT null,  -- Regular season or playoff
    round_phase VARCHAR(255) DEFAULT null,  -- If playoff or COPA, round of the game (quarter final, semifinal, final)

    -- Final score including extra time.
    score_home INTEGER,
    score_away INTEGER,
    -- Score in first quarter.
    score_home_first INTEGER,
    score_away_first INTEGER,
    -- Score in second quarter.
    score_home_second INTEGER,
    score_away_second INTEGER,
    -- Score in third quarter.
    score_home_third INTEGER,
    score_away_third INTEGER,
    -- Score in fourth quarter.
    score_home_fourth INTEGER,
    score_away_fourth INTEGER,
    -- Score in extra-time. Most likely NULL.
    score_home_extra INTEGER,
    score_away_extra INTEGER,

    venue VARCHAR(255) DEFAULT null,  -- Place of the game, stadium
    attendance INTEGER DEFAULT null,  -- Game attendance
    kickoff_time DATETIME DEFAULT null,  -- Kick-off time. In number of seconds since UNIX epoch, UTC timezone.

    FOREIGN KEY (team_home_id) REFERENCES team(id),
    FOREIGN KEY (team_away_id) REFERENCES team(id),

    -- True flag if all the information with respect to the game has been inserted correctly.
    db_flag BOOLEAN DEFAULT 0
);
CREATE INDEX game_team_home_id_idx ON game(team_home_id);
CREATE INDEX game_team_away_id_idx ON game(team_away_id);

/* An actor is a player or a coach. In this table, many fields may be set to NULL. */
CREATE TABLE actor (
    id VARCHAR(12) NOT NULL, -- Combination of category and acb_id (e.g. P20209873 for a player).
    acb_id INTEGER,  -- ACB player / coach ID.
    category VARCHAR(255),
    display_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT null,
    full_name VARCHAR(255) CHARACTER SET utf8mb4,
    nationality VARCHAR(255) DEFAULT null,
    birth_place VARCHAR(255) DEFAULT null,
    birth_date DATETIME DEFAULT null,  -- Date of birth. In number of seconds since UNIX epoch, UTC timezone.
    position VARCHAR(255) DEFAULT null,  -- simple string
    height REAL DEFAULT null,  -- In centimeters.
    weight REAL DEFAULT null,  -- In kilograms.
    license VARCHAR(255) DEFAULT null,
    debut_acb DATETIME DEFAULT null,
    twitter VARCHAR(255) DEFAULT null,
    instagram VARCHAR(255) DEFAULT null,
    PRIMARY KEY(id)
);
CREATE INDEX actor_display_name_idx ON actor(display_name);

-- Table with the actors and names
CREATE TABLE actorname (
    actor_id VARCHAR(12) NOT NULL,
    team_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    name VARCHAR(510) NOT NULL,  -- Name of the player
    FOREIGN KEY (actor_id) REFERENCES actor(id),
    FOREIGN KEY (team_id) REFERENCES team(id),
    PRIMARY KEY(actor_id, team_id, season, name)

);
CREATE INDEX actorName_actor_id_idx ON actorname(actor_id);

/* A participant is a player, a coach or a referee. In this table, many fields may be set to NULL. */
CREATE TABLE participant (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,  -- Table autogenerated id
    game_id INTEGER NOT NULL,
    actor_id VARCHAR(12) NOT null,
    team_id INTEGER NOT null,

    display_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT null,  -- Display name of the actor

     -- Category of the actor
    category VARCHAR(255) DEFAULT null,
    -- Squad number of the player
    number INTEGER DEFAULT null,

    -- True if the player starts the game.
    is_starter BOOLEAN DEFAULT null,

     -- Number of minutes played.
    minutes INTEGER DEFAULT null,
    points INTEGER DEFAULT null,

    -- Two points attempts and scored.
    t2_attempt INTEGER DEFAULT null,
    t2 INTEGER DEFAULT null,
    -- Three points attempts and scored.
    t3_attempt INTEGER DEFAULT null,
    t3 INTEGER DEFAULT null,
     -- Free shots attempts and scored.
    t1_attempt INTEGER DEFAULT null,
    t1 INTEGER DEFAULT null,

    -- Offensive and deffensive rebounds
    defensive_reb INTEGER DEFAULT null,
    offensive_reb INTEGER DEFAULT null,
    -- Assist
    assist INTEGER DEFAULT null,
    -- Steals and turnovers
    steal INTEGER DEFAULT null,
    turnover INTEGER DEFAULT null,
    -- Counterattacks
    counterattack INTEGER DEFAULT null,
    --  Blocks and received blocks
    block INTEGER DEFAULT null,
    received_block INTEGER DEFAULT null,
    -- Dunks
    dunk INTEGER DEFAULT null,
    -- Faults and received faults
    fault INTEGER DEFAULT null,
    received_fault INTEGER DEFAULT null,
    -- +/- ratio. NULL for old matches.
    plus_minus INTEGER DEFAULT null,
    -- Efficiency.
    efficiency INTEGER DEFAULT null,

    possessions INTEGER DEFAULT null,

    FOREIGN KEY (game_id) REFERENCES game(id),
    FOREIGN KEY (team_id) REFERENCES team(id),
    FOREIGN KEY (actor_id) REFERENCES actor(id),
    UNIQUE(game_id, team_id, actor_id)
);
CREATE INDEX participant_game_id_idx ON participant(game_id);
CREATE INDEX participant_team_id_idx ON participant(team_id);
CREATE INDEX participant_actor_id_idx ON participant(actor_id);

CREATE TABLE event (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,  -- Table autogenerated id
    game_event_id INTEGER NOT NULL,  -- Id associated to the game in events website
    game_acb_id INTEGER NOT NULL,  -- Id of the game as in table Game
    team_id INTEGER DEFAULT null,  -- Reference to the team id (some may not have it)
    legend VARCHAR(255) DEFAULT null,
    extra_info VARCHAR(255) DEFAULT null,
    elapsed_time INTEGER DEFAULT null,
    jersey INTEGER DEFAULT null,
    actor_id VARCHAR(12) DEFAULT null,  -- Reference to the actor id (some may not have it)
    home_score INTEGER DEFAULT null,
    away_score INTEGER DEFAULT null,
    roster_home VARCHAR(255) DEFAULT null,
    roster_away VARCHAR(255) DEFAULT null,
    FOREIGN KEY (game_acb_id) REFERENCES game(id),
    FOREIGN KEY (team_id) REFERENCES team(id),
    FOREIGN KEY (actor_id) REFERENCES actor(id)
    );
CREATE INDEX event_game_acb_id_idx ON event(game_acb_id);
CREATE INDEX event_game_event_id_idx ON event(game_event_id);

CREATE TABLE roster (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    event_id INTEGER NOT NULL,
    actor_id VARCHAR(12) DEFAULT null,  -- Reference to the actor id (some may not have it)
    FOREIGN KEY (event_id) REFERENCES event(id),
    FOREIGN KEY (actor_id) REFERENCES actor(id)
    );
CREATE INDEX event_id_idx ON roster(event_id);
CREATE INDEX actor_id_idx ON roster(actor_id);

CREATE TABLE predictions (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    team_home VARCHAR(255) NOT NULL,
    team_home_id INTEGER NOT NULL,
    team_away VARCHAR(255) NOT NULL,
    team_away_id INTEGER NOT NULL,
    kickoff_time DATETIME DEFAULT null,
    season INTEGER DEFAULT null,
    journey INTEGER DEFAULT null,
    prediction DOUBLE DEFAULT null,
    prediction_date DATETIME DEFAULT null,
    model VARCHAR(255) DEFAULT null,
    FOREIGN KEY (team_home_id) REFERENCES team(id),
    FOREIGN KEY (team_away_id) REFERENCES team(id)
);

CREATE TABLE shotchart (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    shotchart_game_acbid INTEGER NOT NULL,
    game_acbid INTEGER NOT NULL,
    team_id INTEGER DEFAULT null,
	actor_id VARCHAR(12) DEFAULT null,
	jersey INTEGER DEFAULT null,
    scored INTEGER DEFAULT null,
    period varchar(30) DEFAULT null,
	shot varchar(30) DEFAULT null,
    shot_type varchar(30) DEFAULT null,
    bottom_px DOUBLE DEFAULT null,
    left_px DOUBLE DEFAULT null,
    bottom_px_adjust DOUBLE DEFAULT null,
    left_px_adjust DOUBLE DEFAULT null,
    left_m_adjust DOUBLE DEFAULT null,
    bottom_m_adjust DOUBLE DEFAULT null,
    distance DOUBLE DEFAULT null,

    FOREIGN KEY (game_acbid) REFERENCES game(id),
    FOREIGN KEY (team_id) REFERENCES team(id),
    FOREIGN KEY (actor_id) REFERENCES actor(id)
    );
CREATE INDEX shotchart_game_id_idx ON shotchart(game_acbid);
CREATE INDEX shotchart_shotchart_id_idx ON shotchart(shotchart_game_acbid);
